const RESERVED_COMPONENTS = new Set([
  "worktrees",
  "repo.git",
  "index",
  "metadata.json",
  "lock",
  "sessions",
  "checkpoints",
]);

function isHexSha(value: string): boolean {
  return /^[a-f0-9]{64}$/u.test(value);
}

/** Validate a path/ref component before using it in checkpoint storage. */
export function isSafeStorageComponent(value: string): boolean {
  if (value.length === 0) return false;
  if (value === "." || value === "..") return false;
  if (value.includes("/") || value.includes("\\")) return false;
  for (const char of value) {
    const code = char.charCodeAt(0);
    if (code < 32 || code === 127) return false;
  }
  if (RESERVED_COMPONENTS.has(value)) return false;
  return true;
}

/** Encode external ids into strict git-ref-safe storage components. */
export function encodeStorageComponent(value: string): string {
  const encoded = Buffer.from(value, "utf8").toString("base64url");
  /* c8 ignore next 3 -- base64url output is safe under current component rules; guard protects future rule changes. */
  if (!isSafeStorageComponent(encoded)) {
    throw new Error("Unsafe checkpoint storage component");
  }
  return encoded;
}

/** Validate Worktree ID components generated by the resolver. */
export function validateWorktreeId(value: string): string {
  if (!isHexSha(value) || !isSafeStorageComponent(value)) {
    throw new Error("Unsafe worktree id");
  }
  return value;
}

const CHECKPOINT_REF_PATTERN =
  /^refs\/ayu\/checkpoints\/sessions\/([^/]+)\/([^/]+)\/(before|after)$/u;

/** Return whether a git ref is a safe checkpoint session-entry ref. */
export function isSafeCheckpointRef(ref: string): boolean {
  const match = CHECKPOINT_REF_PATTERN.exec(ref);
  if (!match) return false;
  const session = match[1];
  const entry = match[2];
  return (
    session !== undefined &&
    entry !== undefined &&
    isSafeStorageComponent(session) &&
    isSafeStorageComponent(entry)
  );
}

/** Build a protected session-entry checkpoint ref. */
export function createCheckpointRef(
  sessionId: string,
  userEntryId: string,
  position: "before" | "after",
): string {
  return `refs/ayu/checkpoints/sessions/${encodeStorageComponent(sessionId)}/${encodeStorageComponent(userEntryId)}/${position}`;
}
